spring:
 datasource:
  url: jdbc:sqlserver://subcontratacion.database.windows.net:1433;database=CDLS_System;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  username: dev
  password: Subcon2021
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
   dialect : org.hibernate.dialect.SQLServer2012Dialect
